package git

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/cockroachdb/errors"
)

// Git handles git config operations.
type Git struct {
	globalConfigPath string
}

// NewGit creates a new Git instance.
func NewGit(globalConfigPath string) *Git {
	return &Git{
		globalConfigPath: globalConfigPath,
	}
}

// WriteConfig writes configuration to git global config.
func (g *Git) WriteConfig(config map[string]any) error {
	content := buildGitConfig(config)
	if err := os.WriteFile(g.globalConfigPath, []byte(content), 0o644); err != nil {
		return errors.Wrap(err, "failed to write git config")
	}

	return nil
}

// BackupConfig creates a backup of the git config.
func (g *Git) BackupConfig(backupPath string) error {
	data, err := os.ReadFile(g.globalConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // No config to backup
		}

		return errors.Wrap(err, "failed to read git config for backup")
	}

	if err := os.WriteFile(backupPath, data, 0o644); err != nil {
		return errors.Wrap(err, "failed to create backup")
	}

	return nil
}

// WriteProfileFile writes a flat key→value git config map to `path` using
// atomic temp-file-and-rename semantics.
//
// Receiver `g` is unused here; the method form is kept for API symmetry
// with WriteRootConfig and Regenerate, which do consume receiver state.
func (g *Git) WriteProfileFile(path string, config map[string]any) error {
	content := buildGitConfig(config)

	return atomicWrite(path, []byte(content))
}

// atomicWrite writes data to a sibling `.tmp` file then renames it into place.
// The rename is atomic with respect to concurrent readers (same-filesystem
// rename(2) on POSIX). It is NOT crash-safe: there is no fsync, so a power
// loss between write and rename can leave a partial file.
func atomicWrite(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return errors.Wrap(err, "failed to write temp file")
	}

	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)

		return errors.Wrap(err, "failed to rename temp file into place")
	}

	return nil
}

// rootConfigHeader is emitted at the top of the generated ~/.gitconfig.
// Used both to inform users that the file is managed and (optionally in
// the future) to detect prior generations.
const rootConfigHeader = "# Generated by git-context — do not edit. " +
	"Run `git-context` to manage.\n"

// WriteRootConfig generates the ~/.gitconfig manifest:
//   - a header marker
//   - one unconditional [include] block for `defaultProfilePath`, if set
//   - one [includeIf "gitdir:<path>"] block per (path → profile-file) entry
//
// `assignments` keys are normalized directory paths (with trailing `/`),
// values are absolute paths to per-profile gitconfig files. Blocks are
// emitted in sorted key order so output is deterministic.
//
// If the default is empty AND assignments is empty, no file is written
// (avoids clobbering an existing user-managed ~/.gitconfig before any
// git-context state exists).
func (g *Git) WriteRootConfig(defaultProfilePath string, assignments map[string]string) error {
	if defaultProfilePath == "" && len(assignments) == 0 {
		return nil
	}

	var b strings.Builder

	b.WriteString(rootConfigHeader)
	b.WriteString("\n")

	if defaultProfilePath != "" {
		fmt.Fprintf(&b, "[include]\n\tpath = %s\n\n", defaultProfilePath)
	}

	keys := make([]string, 0, len(assignments))
	for k := range assignments {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	for _, dir := range keys {
		fmt.Fprintf(&b, "[includeIf \"gitdir:%s\"]\n\tpath = %s\n\n", dir, assignments[dir])
	}

	return atomicWrite(g.globalConfigPath, []byte(b.String()))
}

// buildGitConfig builds git config format from a map of key-value pairs.
// It handles both regular dotted notation and quoted subsections.
// Returns a formatted git config string with sections and key-value pairs.
//
//nolint:nestif
func buildGitConfig(config map[string]any) string {
	var content strings.Builder

	sectionMap := make(map[string]map[string]any)

	// Group keys by section
	for key, value := range config {
		// Handle quoted subsections like url."pattern".insteadof
		var section, keyName string

		if strings.Contains(key, "\"") {
			// This is a quoted subsection like url."ssh://git@gitlab.molops.io/".insteadof
			// Extract the section with the quoted part intact
			lastDotIdx := strings.LastIndex(key, ".")
			if lastDotIdx > 0 {
				section = key[:lastDotIdx]
				keyName = key[lastDotIdx+1:]
			} else {
				continue
			}
		} else {
			// Regular dot notation
			parts := strings.Split(key, ".")
			if len(parts) >= 2 {
				section = strings.Join(parts[:len(parts)-1], ".")
				keyName = parts[len(parts)-1]
			} else {
				continue
			}
		}

		if sectionMap[section] == nil {
			sectionMap[section] = make(map[string]any)
		}

		sectionMap[section][keyName] = value
	}

	// Write sections
	for section, values := range sectionMap {
		fmt.Fprintf(&content, "[%s]\n", section)

		for k, v := range values {
			fmt.Fprintf(&content, "\t%s = %v\n", k, v)
		}

		content.WriteString("\n")
	}

	return content.String()
}
